In [ ]:
#Optimizaion

In [8]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [14]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [15]:
import numpy as np

In [9]:
from scipy.optimize import minimize

In [10]:
ans = minimize(lambda x: x**2 + 1, method = 'nelder-mead', x0=10)

In [11]:
ans

       message: Optimization terminated successfully.
       success: True
        status: 0
           fun: 1.0
             x: [ 0.000e+00]
           nit: 21
          nfev: 42
 final_simplex: (array([[ 0.000e+00],
                       [-6.104e-05]]), array([ 1.000e+00,  1.000e+00]))

In [12]:
ans.x#مقدار X

array([0.])

In [13]:
ans.fun#مقدار تابع

1.0

In [20]:
# ans = minimize(lamba x: np.sum(x**2)+ 1, method = 'nelder=mead', x0=np.array([10, 10]))#توابع چند متغییره
# print(ans.message)#np.array([10, 10, 10, 10])Whoul be 3 or 4 dimenssional
ans = minimize(lambda x: np.sum(x**2) + 1, method = 'nelder-mead', x0=np.array([10, 10]))
print(ans.message)

Optimization terminated successfully.


In [21]:
ans

       message: Optimization terminated successfully.
       success: True
        status: 0
           fun: 1.0000000006830416
             x: [ 1.496e-05  2.143e-05]
           nit: 46
          nfev: 83
 final_simplex: (array([[ 1.496e-05,  2.143e-05],
                       [-6.661e-05, -3.877e-05],
                       [-4.350e-05,  6.962e-05]]), array([ 1.000e+00,  1.000e+00,  1.000e+00]))

In [22]:
#(x + 2y - y)^2 + (2x + y - 5)^2

In [23]:
def f(x):
    return( x[0] + 2*x[1] - 7)**2 + (2*x[0] + x[1] - 5)**2

In [24]:
ans = minimize(lambda x: np.sum(x**2) + 1, method = 'nelder-mead', x0=np.array([10, 10]))
print(ans.message)
print(ans.x, ans.fun)

Optimization terminated successfully.
[1.49644896e-05 2.14267502e-05] 1.0000000006830416


In [25]:
ans = minimize(lambda x: (x[0] + 2*x[1] - 7)**2 + (2*x[0] + x[1] - 5)**2, method = 'nelder-mead', x0=np.array([10, 10]))
print(ans.message)
print(ans.x, ans.fun)

Optimization terminated successfully.
[1.00000346 3.00001143] 1.029458242212379e-09


In [28]:
ans

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 1.0
       x: [-2.114e-13 -2.114e-13 -2.114e-13 -2.114e-13]
     nit: 1
     jac: [-4.228e-13 -4.228e-13 -4.228e-13 -4.228e-13]
    nfev: 4
    njev: 4

In [26]:
ans = minimize(lambda x: np.sum(x**2) + 1,
               method = 'CG',
               x0=np.array([10, 10, 10, 10]),
              jac=lambda x : 2*x)
print(ans.message)
print(ans.x, ans.fun)

Optimization terminated successfully.
[-2.11386464e-13 -2.11386464e-13 -2.11386464e-13 -2.11386464e-13] 1.0


In [27]:
ans

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 1.0
       x: [-2.114e-13 -2.114e-13 -2.114e-13 -2.114e-13]
     nit: 1
     jac: [-4.228e-13 -4.228e-13 -4.228e-13 -4.228e-13]
    nfev: 4
    njev: 4

In [ ]:
#Gradient algorithms have a high Basiler convergence coefficient

In [29]:
def Beale(x):
    return( 1.5 - x[0] + x[0]*x[1])**2 + ( 2.25 - x[0] + x[0]*x[1]**2)**2 + ( 2.625 - x[0] + x[0]*x[1]**3)**2
print(ans.message)
print(ans.x, ans.fun)

Optimization terminated successfully.
[-2.11386464e-13 -2.11386464e-13 -2.11386464e-13 -2.11386464e-13] 1.0


In [32]:
ans = minimize(Beale,
               method = 'nelder-mead',
               x0=np.array([10, 10]))
              
print(ans.message)
print(ans.x, ans.fun)    

Optimization terminated successfully.
[2.9999593  0.49998973] 2.659159941599466e-10


In [31]:
ans

       message: Optimization terminated successfully.
       success: True
        status: 0
           fun: 2.659159941599466e-10
             x: [ 3.000e+00  5.000e-01]
           nit: 97
          nfev: 185
 final_simplex: (array([[ 3.000e+00,  5.000e-01],
                       [ 3.000e+00,  5.000e-01],
                       [ 3.000e+00,  5.000e-01]]), array([ 2.659e-10,  3.761e-10,  2.268e-09]))

In [ ]:
#The starting point should be close to the optimum point, and if not, the function may not be able to optimize